app/models.py
# Flask modules
from flask_login import UserMixin

# Other modules
from datetime import datetime

# Local modules
from app.extensions import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, unique=True, nullable=False)
    name = db.Column(db.String(80), nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    created_date = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f'<User {self.name}>'


__all__ = [User, ]

app/forms.py
# Flask modules
from flask_wtf import FlaskForm
from wtforms.validators import ValidationError
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length, Regexp

# Local modules
from app.models import User


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()], render_kw={'placeholder': 'example@email.com'})
    password = PasswordField('Password', validators=[DataRequired()], render_kw={'placeholder': '********'})
    remember_me = BooleanField('Remember me', default=False)
    submit = SubmitField('Log In')


class RegistrationForm(FlaskForm):
    name = StringField('Name', validators=[
        DataRequired(),
        Length(min=2, max=80),
        Regexp(r'^[a-zA-Z0-9_]+$', message='Name must contain only letters, numbers, and underscores.')],
                       render_kw={'placeholder': 'Display name'})
    email = StringField('Email', validators=[
        DataRequired(),
        Email()
    ], render_kw={'placeholder': 'example@email.com'})
    password = PasswordField('Password', validators=[
        DataRequired(),
        Length(min=8),
    ], render_kw={'placeholder': 'Enter your password'})
    confirm_password = PasswordField('Confirm Password', validators=[
        DataRequired(),
        EqualTo('password', message='Passwords must match')
    ],
                                     render_kw={'placeholder': 'Confirm your password'})
    submit = SubmitField('Register')

    def validate_email(self, email):
        existing_user = User.query.filter_by(email=email.data).one_or_none()
        if existing_user:
            raise ValidationError('Email address already registered.')

    def validate_password(self, password):
        if not any(c.isalpha() for c in password.data) or not any(c.isdigit() for c in password.data):
            raise ValidationError('Password must contain at least one letter and one digit.')

app/__init__.py
# Flask modules
from flask import Flask


def create_app(debug: bool = False) -> Flask:
    # Initialize app
    app = Flask(__name__, template_folder='../templates', static_folder='../static', static_url_path='/')

    # Setup app configs
    app.config['DEBUG'] = debug
    app.config['SECRET_KEY'] = "YOUR-SECRET-KEY-HERE"
    app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///database.db"

    # Initialize extensions
    from app.extensions import db, bcrypt, csrf, login_manager
    db.init_app(app)
    csrf.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    # Create database tables
    from app import models
    with app.app_context():
        db.create_all()

    # Register blueprints
    from app.routes import routes_bp
    app.register_blueprint(routes_bp)

    return app

app/routes.py
# Flask modules
from flask import Blueprint, redirect, url_for, render_template, flash
from flask_login import login_user, logout_user, current_user, login_required

# Local modules
from app.models import User
from app.extensions import db, bcrypt, login_manager
from app.forms import LoginForm, RegistrationForm

routes_bp = Blueprint('routes', __name__, url_prefix="/")


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).one_or_none()


@routes_bp.route("/")
@login_required
def home():
    return render_template('index.html')


@routes_bp.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("routes.home"))

    form = LoginForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        remember_me = form.remember_me.data

        user = User.query.filter_by(email=email).one_or_none()
        if user and bcrypt.check_password_hash(user.password, password):
            login_user(user, remember=remember_me)
            flash(f"Logged in successfully as {user.name}", 'success')
            return redirect(url_for("routes.home"))
        else:
            flash("Invalid email or password", 'danger')

    return render_template('auth/login.html', form=form)


@routes_bp.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("routes.home"))

    form = RegistrationForm()

    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data

        hashed_password = bcrypt.generate_password_hash(password)

        # Add user to database
        new_user = User(name=name, email=email, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()

        # Login user
        login_user(new_user)

        flash(f'Account created successfully! You are now logged in as {new_user.name}.', 'success')
        return redirect(url_for("routes.home"))

    return render_template('auth/register.html', form=form)


@routes_bp.route("/logout", methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for("routes.login"))

main.py
from app import create_app

app = create_app()

if __name__ == '__main__':
    app.run(debug=True)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <link rel="icon" href="/images/favicon.ico"/>
    <!-- CSS -->
    <link rel="stylesheet" href="/css/main.css"/>
    <!-- JAVASCRIPT -->
    <script src="/js/main.js" defer></script>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
{% with messages = get_flashed_messages(with_categories=true, category_filter=["success", "info"]) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }}" style="width: 100%; z-index: 999">
    {{ message }}
      <a class="close" href="#" onclick="this.parentElement.remove(); return false">×</a>
</div>
{% endfor %}
{% endif %}
{% endwith %}
<main class="p-2">
    {% block content %}
    {% endblock content %}
</main>

<!-- Include Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}
<h1>Home Page</h1>
<p>Hello there, you are logged in as <span class="text-success font-weight-bold">{{ current_user.name }}</span>.</p>
<a href="{{ url_for('routes.logout') }}">Logout</a>
{% endblock content %}